### ISSUE TITLE
Dark mode problems on Mac OS

### ISSUE THREAD

**Issue by pjamessteven** [green0range/timetables#11]
Fonts are illegible on Mac OS when system dark mode is enabled (QT framework must detect it and change the font color, but the app background doesn't change. When the system is set to light mode it runs fine :D

The same thing might happen when dark mode is enabled on Windows?

![Screen Shot 2022-01-29 at 12 56 54 AM](https://user-images.githubusercontent.com/19263848/151543195-5d951512-af36-44b4-868b-c0bc6b763577.png)

**Comment by green0range** [comment]
Some of the styling parameters are set (in style.css) which is why the background is still white in dark mode, however I have missed some parameters so they are set to the default. 

The styling has 3 purposes:
1. it sets the colour-coding of the routes, once you add them.
2. it makes it look less like a generic qt application
3. it makes the experience more consistent

2 and 3 definitely need some more work as pointed out by this bug.

The options are:
1. Remove styling for everything except routes and let the OS decide on all the colours. However I think the map is generated with a white background (using PIL, not QT) so that would need to be changed.
2. Make the styling more complete so the OS can't decide any of the colours. There could also be an alternative style for dark mode.

A quick work round is of course to remove some lines from style.css
